### ISSUE TITLE
The names and number of resources do not change.

### ISSUE THREAD

**Issue by TrexMonster** [ardittristan/5eSheet-resourcesPlus#40]
Same problem as in issue #39.
The names and number of resources do not change.
(for all resources starting from 4).
dnd 3.0.3, foundry 11.315

**Comment by MotoMoto1234** [comment]
This is because of how 5e resources+ registers its data.  The module dynamic effects using active effects tosses the data out on character view.  Tposney has been made aware, not sure if hes going to try and fix things on that end or submit a PR here for this author to change where they are placing the data.

**Comment by MotoMoto1234** [comment]
You can mark this issue as solved, it was a conflict with dynamic effects using active effects and the author of that module has released a version that fixes the bad interaction.  You can now use resources plus with dae as of dae version 11.3.11.
