### ISSUE TITLE
Request Feature: Cogwheel moved

### ISSUE THREAD

**Issue by Bryn1701** [ardittristan/5eSheet-resourcesPlus#7]
First of all, this is great! It's exactly what I needed. As the title says. I would love to have the resource count cogwheel move below all the favourited items, so it doesn't take up valuable room at the top.

**Comment by ardittristan** [comment]
![image](https://user-images.githubusercontent.com/42787508/96143902-e1a5f380-0f03-11eb-8abc-37aac61ea6ea.png)
Do you mean this with resource count cogwheel? if yes I could probably relocate it to the header of the sheet application.

**Comment by Bryn1701** [comment]
I would love to see it at the bottom personally. Here is a very quick mock up of it. https://i.imgur.com/cbV4pkz.jpg

**Comment by ardittristan** [comment]
I feel like that would take way too much space, since currently it's only that wide if there's an amount of resources divisible by 3. What do you think of adding it in this menu?
![image](https://user-images.githubusercontent.com/42787508/96194385-83e8ca00-0f4a-11eb-8353-17d2f517d7fe.png)
Since that menu is already sheet settings anyway

**Comment by Bryn1701** [comment]
That would be ever better! Yeah

**Comment by ardittristan** [comment]
added in 1.6.0, and enabled by default.
